//
// Created by morimoto_hibiki on 2025/10/08.
//

#ifndef AHO_ALL_VSL_H
#define AHO_ALL_VSL_H

#include "type.hpp"
#include "window_plugin.hpp"
#include "define.hpp"
#include "exceptions.hpp"
#include "consteval_string.hpp"
#include "test.hpp"
#include "window.hpp"
#include "utils/flags.hpp"
#include "utils/string.hpp"
#include "utils/vsl_array.hpp"
#include "dimension.hpp"
#include "vulkan/vulkan.hpp"
#include "vulkan/synchronize.hpp"
#include "vulkan/window_plugin/hook_window_resize.hpp"
#include "vulkan/device.hpp"
#include "vulkan/descriptor_set_manager.hpp"
#include "vulkan/shader.hpp"
#include "vulkan/surface.hpp"
#include "vulkan/stages/multisample.hpp"
#include "vulkan/stages/color_blend.hpp"
#include "vulkan/stages/dynamic_state.hpp"
#include "vulkan/stages/vertex_input.hpp"
#include "vulkan/stages/rasterization.hpp"
#include "vulkan/stages/depth_stencil.hpp"
#include "vulkan/stages/input_assembly.hpp"
#include "vulkan/stages/shader_group.hpp"
#include "vulkan/stages/resource_binding.hpp"
#include "vulkan/stages/push_contents.hpp"
#include "vulkan/stages/id_picking.hpp"
#include "vulkan/viewport.hpp"
#include "vulkan/scissor.hpp"
#include "vulkan/swapchain.hpp"
#include "vulkan/sampler.hpp"
#include "vulkan/pv.hpp"
#include "vulkan/buffer.hpp"
#include "vulkan/pipeline.hpp"
#include "vulkan/commands/bind_index_buffers.hpp"
#include "vulkan/commands/bind_pipe_line.hpp"
#include "vulkan/commands/render_pass_end.hpp"
#include "vulkan/commands/draw_indexed.hpp"
#include "vulkan/commands/bind_vertex_buffers.hpp"
#include "vulkan/commands/bind_graphic_resource.hpp"
#include "vulkan/commands/render_pass_begin.hpp"
#include "vulkan/commands/push_content.hpp"
#include "vulkan/commands/draw.hpp"
#include "vulkan/commands/draw_indexed_instance.hpp"
#include "vulkan/command.hpp"
#include "vulkan/render_pass.hpp"
#include "vulkan/frame_buffer.hpp"
#include "vulkan/pipeline_layout.hpp"
#include "format.hpp"
#include "concepts.hpp"

#ifdef VSL_ENABLE_SPIRV_REFLECTOR
#include "utils/spir_reflector.hpp"
#endif
#include "vulkan/post_definition.hpp"

#endif //AHO_ALL_VSL_H
